### ISSUE TITLE
Prevent overlay stacking when multiple windows showing

### ISSUE THREAD

**Issue by freon27** [KevCJones/ngx-simple-modal#22]
Me again. Sorry, but hopefully it's a less painful question.

I noticed that with your local styles, when we show multiple windows at the same time, the semi-opaque overlay is also duplicated with the result that the more windows we show, the darker it gets (down to black within about 4 windows). 

Is there any way to prevent this stacking effect so that it's only the windows that are repeated rather than the screen overlay?  Or do I need to resolve  this in the CSS somehow?

**Comment by KevCJones** [comment]
Well tbh, the way that the system works at the moment is that the modal holder contains the modal component you implement, and its this 'holder' which has the backdrop style on. 

Since the modal you open over another needs to have a click blocking backdrop to the one below normally then i don't think moving where the backdrop lives is the answer. 

Something like 

```
.modal {
    ...
    background-color: transparent;
}

simple-modal-wrapper:last-of-type .modal {
  background-color:rgba(0,0,0,.4);
}

```

Might get you there, but honestly i think if you have fading in and fading out animation you might see a flicker. You'd need to tackle that in your own preferred way if that comes along. 

If i wanted to address this in the future as an improvement i'd have to manage the compexity of having one modal backdrop inside container and then managing z-index of multiple modals manually.. not something it supports right now.

**Comment by KevCJones** [comment]
You're welcome to take a stab at this btw, or anyone else.  I'm starting a new job in mid Feb so either side of that is going to be pretty busy for me as a ramp down and back up again. If someone does plan on it, announce it here, if i don't see an announcement i'll self assign to explore when i can. 

The prime requirements right now are that the solution needs to be clean and not require any complexity in the users domain and not too much to maintain in ours.

**Comment by freon27** [comment]
Thanks. I'll probably have to wait for it to get scheduled as an enhancement at work to get time to work on this but if I do, then I try to make it generic so that I can send you a pull request.

**Comment by KevCJones** [comment]
Nice one...

In related interesting news.. HTML 5.2 has specified a native HTML dialog - [https://bitsofco.de/whats-new-in-html-5-2/](https://bitsofco.de/whats-new-in-html-5-2/)

[https://caniuse.com/#feat=dialog](https://caniuse.com/#feat=dialog)
With reference to `Also includes a ::backdrop pseudo-element for behind the element.` i'll be curious to see if their's also stacks or not.

**Comment by KevCJones** [comment]
Closing this for now. I did a little test now and even without a HTML restructure i was able to get the desired effect using CSS nth-child selection on the component to control the background classes visibility. Since a design decision of this was to stay as unopinionated as possible re: CSS choices. The conttrol is anyone's hand to do as they will. Changing this for one set of users will only involve forcing another set to counter it to their own tastes. I think i could do some work later to make this a configurable thing and welcome pull requests that make it a simple switch between the two.
