### ISSUE TITLE
How to work on background when modal is opened

### ISSUE THREAD

**Issue by Navyasri-Gurram** [KevCJones/ngx-simple-modal#43]
I am new to  modals in angular. my requirement is to work on background when my modal popup is opened and i need to set my custom styles to the modal. But couldn't apply when i am creating separate css for each components modals. Effecting all modals if i declare css globally

**Comment by KevCJones** [comment]
So, I'm not sure if I understand the problem yet but, for the baseline CSS
I recommend you create a global default. Add to yours styles.[s]css file or
as the README suggests , create a separate file and include in the styles
section of your angular config file.

You have the option to set classes for background on a per modal basis if
you need to change the behaviour.

Since the modal itself is created lazily, and then added as a child to a
dynamically created wrapper which is where the background lives, setting a
CSS  class to override  default is the way to currently target background
colour and style.

In my experience, most projects pick a single style for the background so I
didn't expand it beyond this. I am willing to consider if you make a clear
outline of your feature request though.

Best

K

**Comment by Navyasri-Gurram** [comment]
Sorry for the late. Thank you it worked i have created my css globally. 👍

**Comment by KevCJones** [comment]
No worries, glad that helped
