### ISSUE TITLE
Doesn't work in Angular 8.1 --prod mode

### ISSUE THREAD

**Issue by energY8989** [KevCJones/ngx-simple-modal#54]
I receive an error when i build with **--prod** option. Without, it works.
I am getting the following Java-Script errormessage:

"this.viewContainer is undefined"

**Comment by vladk** [comment]
I have same error

**Comment by KevCJones** [comment]
Yeah I've seen it, working on it now.

**Comment by KevCJones** [comment]
Thanks for the heads up - ironically we were about to push our own work into production and 15 minutes later as we hit smoke tests in our staging production server, the same messages hit my inbox. 

Fixed in 1.3.15 - I've left the `demo-ng8` in --prod mode for anyone who wants to see it working.

It always pays to test in prod mode as well 🤦‍♂ but it's been a while since I've had a prod specific issue.
